// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function LoadConversationsFromPath(arg1:string):Promise<Array<models.ConversationEntry>>;

export function OpenConversationsFile():Promise<Array<models.ConversationEntry>>;
