// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConversationsFromPath(arg1) {
  return window['go']['main']['App']['LoadConversationsFromPath'](arg1);
}

export function OpenConversationsFile() {
  return window['go']['main']['App']['OpenConversationsFile']();
}
